In [34]:
import csv
import pandas as pd
from sklearn.cross_validation import train_test_split

In [35]:
example = pd.read_csv('example.csv')

In [27]:
example.head()

,Unnamed: 0,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,RFCD.Code.3,...,Dept.No..1,Faculty.No..1,With.PHD.1,No..of.Years.in.Uni.at.Time.of.Grant.1,Number.of.Successful.Grant.1,Number.of.Unsuccessful.Grant.1,A..1,A.1,B.1,C.1
0,0,1,0.0,0.0,1.0,280199.0,100.0,0.0,0.0,0.0,...,3073.0,31.0,0.0,1.0,0.0,0.0,4.0,2.0,0.0,0.0
1,1,1,2.0,1.0,2.0,280103.0,30.0,280106.0,30.0,280203.0,...,2538.0,25.0,1.0,2.0,0.0,0.0,6.0,12.0,2.0,2.0
2,2,1,29.0,2.0,1.0,321004.0,60.0,321216.0,40.0,0.0,...,2923.0,25.0,1.0,3.0,0.0,0.0,0.0,3.0,5.0,2.0
3,3,1,40.0,2.0,3.0,270602.0,50.0,320602.0,50.0,0.0,...,2678.0,25.0,1.0,3.0,0.0,0.0,0.0,3.0,13.0,3.0
4,4,0,59.0,1.0,1.0,260500.0,34.0,280000.0,33.0,290000.0,...,2153.0,19.0,1.0,3.0,0.0,0.0,3.0,0.0,1.0,0.0

In [36]:
example=example.drop(['Unnamed: 0'], axis=1)

In [29]:
len(example.columns)

38

In [37]:
example.columns=['Label','I1','I2','I3','I4','I5','I6','I7','I8','I9','I10','I11','I12','I13','I14','I15','I16','I17','I18','I19','I20','I21','I22','I23','I24','I25','I26','I27','I28','I29','I30','I31','I32','I33','I34','I35','I36','I37']

In [38]:
 train_df, test_df = train_test_split(example, train_size = 0.8,random_state=42)

In [39]:
train_df.to_csv('tr.csv',index = False)
test_df.to_csv('te.csv',index = False)